steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/veica-infra/caronte-repo/caronte-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/veica-infra/caronte-repo/caronte-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'caronte-app'
      - '--image=us-east1-docker.pkg.dev/veica-infra/caronte-repo/caronte-app:$SHORT_SHA'
      - '--region=us-east1'
      - '--platform=managed'
      - '--port=8080'

images:
  - 'us-east1-docker.pkg.dev/veica-infra/caronte-repo/caronte-app:$SHORT_SHA'